In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])

In [3]:
print(a)

[1 2 3]


In [4]:
type(a)

numpy.ndarray

In [5]:
a.size

3

In [6]:
a.nbytes

12

In [7]:
a.dtype

dtype('int32')

In [8]:
a.shape

(3,)

In [9]:
y=np.array([(1,2,3),(4,5,6),(7,8,9)])

In [10]:
y.shape

(3, 3)

In [11]:
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# LIST VS ARRAY

In [14]:
l1=range(1000)
import sys
sys.getsizeof(5)*len(l1)

28000

In [20]:
a1=np.arange(1000,dtype='int8')
a1.itemsize*a1.size

1000

In [23]:
import time
SIZE=100000
l1=range(SIZE)
l2=range(SIZE)

a1=np.arange(SIZE)
a2=np.arange(SIZE)

start=time.time()
result=[ x+y for x,y in zip(l1,l2)]
end=time.time()

print("LIST TOOK:", (end-start)*1000)

start=time.time()
result=a1+a2
end=time.time()

print("ARRAY TOOK:", (end-start)*1000)


LIST TOOK: 18.608570098876953
ARRAY TOOK: 4.221439361572266


In [24]:
z=np.array([(1,2,3,4),(5,6,7,8)])

In [25]:
z.shape

(2, 4)

In [26]:
z

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
z.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [28]:
z

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [29]:
z=np.array([(1,2,3),(4,5,6),(7,8,9)])

In [30]:
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
z[1,1]

5

In [36]:
z[1,1:3]

array([5, 6])

In [38]:
z[1:,0:2]

array([[4, 5],
       [7, 8]])

In [39]:
z.max()

9

In [41]:
z.min()

1

In [42]:
z.sum()

45

In [43]:
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
z.sum(axis=0)

array([12, 15, 18])

In [45]:
z.sum(axis=1)

array([ 6, 15, 24])

In [46]:
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
np.sqrt(z)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [48]:
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
np.std(z)

2.581988897471611

In [50]:
np.sin(z)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [51]:
np.cos(z)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026]])

In [53]:
np.tan(z)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

In [54]:
np.log(z)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [55]:
np.exp(z)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [56]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [57]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [58]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [59]:
np.full((3,3),100)

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [62]:
np.random.rand(3,3)

array([[0.60093475, 0.94100589, 0.93226595],
       [0.41923309, 0.35021489, 0.06004984],
       [0.16907279, 0.17211928, 0.45418645]])

In [63]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [64]:
a=np.array([1,2,3,4])

In [65]:
a

array([1, 2, 3, 4])

In [66]:
a+2

array([3, 4, 5, 6])

In [68]:
a=np.array([(1,2,3),(4,5,6)])
b=np.array([(1,2,3),(4,5,6)])

In [69]:
a+b

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [70]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
a-b

array([[0, 0, 0],
       [0, 0, 0]])

In [73]:
a.shape

(2, 3)

In [74]:
b.shape

(2, 3)

In [75]:
np.dot(a,b)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [77]:
a=np.array([(1,2,3),(4,5,6),(7,8,9)])
b=np.array([(1,2,3),(4,5,6),(7,8,9)])

In [78]:
a.shape

(3, 3)

In [79]:
b.shape

(3, 3)

In [80]:
np.dot(a,b)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])